=== panedrone/sdm_todolist_go_react_vue_npm_sqlite3/go-sdm/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="settings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="folders"/>
                <xs:element ref="dto"/>
                <xs:element ref="dao"/>
                <xs:element ref="ide"/>
                <xs:element ref="jdbc"/>
                <xs:element ref="type-map"/>
                <xs:element ref="macros"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="folders">
        <xs:complexType>
            <xs:attribute name="target" use="required" type="xs:string"/>
            <xs:attribute name="sql" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dto">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
            <xs:attribute name="inheritance" use="required" type="xs:string"/>
            <xs:attribute name="field-names-mode" use="required" type="xs:int"/>
            <xs:attribute name="macro" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dao">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
            <xs:attribute name="field-assign-mode" use="required" type="xs:int"/>
            <xs:attribute name="macro" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ide">
        <xs:complexType>
            <xs:attribute name="event-log" use="required" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="jdbc">
        <xs:complexType>
            <xs:attribute name="jar" use="optional" type="xs:string"/>
            <xs:attribute name="class" use="optional" type="xs:string"/>
            <xs:attribute name="url" use="required" type="xs:string"/>
            <xs:attribute name="user" use="required" type="xs:string"/>
            <xs:attribute name="pwd" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="type-map">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="type"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="default" use="required"
                          type="xs:string"/>
        </xs:complexType>
        <xs:unique name="type-detected">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@detected"/>
        </xs:unique>
    </xs:element>
    <xs:element name="type">
        <xs:complexType>
            <xs:attribute name="detected" use="required" type="xs:string"/>
            <xs:attribute name="target" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="macros">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="macro">
                        <xs:complexType>
                            <xs:choice minOccurs="0">
                                <xs:element name="vm" type="xs:string" minOccurs="0"/>
                                <xs:element ref="vm-xml" minOccurs="0"/>
                            </xs:choice>
                            <xs:attribute ref="name" use="required"/>
                            <xs:attribute ref="value" use="optional"/>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="macro-name">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:attribute name="var" type="xs:string"/>
    <xs:attribute name="in" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="params" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>

    <xs:complexType name="root-statements">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:choice>
                <xs:element ref="if"/>
                <xs:element ref="set"/>
                <xs:element ref="foreach"/>
                <xs:element ref="macro"/>
                <xs:element ref="print"/>
                <xs:element ref="br"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="vm-xml">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="if">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="elseif" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element ref="else" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="elseif">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="else">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="foreach">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                    <xs:attribute ref="in" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="macro">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="name" use="required"/>
                    <xs:attribute ref="params" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="set">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="print">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="br">
        <xs:complexType>
            <xs:attribute name="br" default="" use="optional"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== panedrone/sdm_todolist_go_react_vue_npm_sqlite3/sqlx/sdm/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!--    (*) below means "a path relative to the project root"   -->

    <!-- target: the same as "module" in "go.mod" -->

    <!-- sql: base folder of SQL files (*) -->

    <folders target="sdm_demo_todolist" sql="sqlx/sdm/sql"/>

    <!-- scope: base folder of generated DTO files (*). -->

    <!-- field-names-mode: 0 - TitleCase -->

    <!-- macro: VM template to render DAO classes

            1. Internal VM template is used if "macro" is empty (default).
            2. VM template is located in "<macros>...<macro><vm>|<vm-xml>..." section below.
            3. Ending ".vm" means using of VM file and specifies the path to this file relative to the project root:
                    <dto ... macro="<path>/<name>.vm"/> -->

    <dto scope="sqlx/dbal/dto" inheritance="" field-names-mode="0" macro=""/>

    <!-- scope: base folder of generated DAO files (*) -->

    <!-- field-assign-mode (Go only)":

            0 - by column name
            1 - by field position
            2 - ptr to DTO or ptr to slice of DTO-s (Gorm, sqlx)
            3 - ptr to resulting slice of DTO-s (Gorm, sqlx) -->

    <!-- macro: VM template to render DAO classes

            1. Internal VM template is used if "macro" is empty (default).
            2. VM template is located in "<macros>...<macro><vm>|<vm-xml>..." section below.
            3. Ending ".vm" means using of VM file and specifies the path to this file relative to the project root:
                    <dao ... macro="<path>/<name>.vm"/> -->

    <dao scope="sqlx/dbal" field-assign-mode="3" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="lib/sqlite-jdbc-3.51.1.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/db/todolist.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

    <!--    <jdbc jar="mysql-connector-j-8.4.0.jar"-->
    <!--          class="com.mysql.cj.jdbc.Driver" url="jdbc:mysql://localhost/orders" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.7.3.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost/orders" user="postgres" pwd="sa"/>-->

    <type-map default="">

        <!-- sqlite3 -->

        <type detected="sqlx-java.lang.Integer" target="int64${json-sqlx} -> SetInt64"/>
        <type detected="sqlx-java.lang.Float" target="float32${json-sqlx} -> SetFloat32"/>
        <type detected="sqlx-java.lang.Double" target="float64${json-sqlx} -> SetFloat64"/>
        <type detected="sqlx-java.lang.String" target="string${json-sqlx} -> SetString"/>
        <type detected="sqlx-java.util.Date" target="time:time.Time${json-sqlx} -> SetTime"/>
        <type detected="sqlx-byte[]" target="byte[]${json-sqlx} -> SetBytes"/>
        <type detected="sqlx-java.lang.Object" target="interface{}${json-sqlx}"/>

        <type detected="java.lang.Integer" target="int64${json} -> SetInt64"/>
        <type detected="java.lang.Float" target="float32${json} -> SetFloat32"/>
        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>
        <type detected="java.lang.String" target="string${json} -> SetString"/>
        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>
        <type detected="byte[]" target="[]byte${json} -> SetBytes"/>
        <type detected="java.lang.Object" target="interface{}${json}"/>

        <!-- mysql, postgres, sql server  -->

        <!--        <type detected="sqlx-java.util.UUID" target="github.com/google/uuid:uuid.UUID${json-sqlx}|1:;type:uuid"/>-->
        <!--        <type detected="sqlx-java.util.UUID+auto"-->
        <!--              target="github.com/google/uuid:uuid.UUID${json-sqlx}|1:;type:uuid;default:uuid_generate_v4()"/>-->

        <!--        <type detected="sqlx-java.sql.Array" target="[]string${json-sqlx}"/>-->

        <!--        <type detected="sqlx-java.lang.Short" target="int16${json-sqlx} -> SetInt16"/>-->
        <!--        <type detected="sqlx-java.lang.Integer" target="int32${json-sqlx} -> SetInt32"/>-->
        <!--        <type detected="sqlx-java.lang.Long" target="int64${json-sqlx} -> SetInt64"/>-->

        <!--        <type detected="sqlx-java.lang.Float" target="float32${json-sqlx} -> SetFloat32"/>-->
        <!--        <type detected="sqlx-java.lang.Double" target="float64${json-sqlx} -> SetFloat64"/>-->
        <!--        <type detected="sqlx-java.math.BigDecimal" target="float64${json-sqlx} -> SetFloat64"/>-->

        <!--        <type detected="sqlx-java.lang.String" target="string${json-sqlx} -> SetString"/>-->
        <!--        <type detected="sqlx-byte[]" target="string${json-sqlx}"/>-->
        <!--        <type detected="sqlx-java.lang.Boolean" target="bool${json-sqlx} -> SetBool"/>-->

        <!--        <type detected="sqlx-java.util.Date" target="time:time.Time${json-sqlx} -> SetTime"/>-->
        <!--        <type detected="sqlx-java.time.LocalDateTime" target="time:time.Time${json-sqlx} -> SetTime"/>-->

        <!--        <type detected="sqlx-java.lang.Object" target="interface{}${json-sqlx}"/>-->

        <!--        <type detected="java.util.UUID" target="github.com/google/uuid:uuid.UUID${json} -> SetUUID"/>-->
        <!--        <type detected="java.sql.Array" target="[]string${json}"/>-->

        <!--        <type detected="java.lang.Short" target="int16${json} -> SetInt16"/>-->
        <!--        <type detected="java.lang.Integer" target="int32${json} -> SetInt32"/>-->
        <!--        <type detected="java.lang.Long" target="int64${json} -> SetInt64"/>-->

        <!--        <type detected="java.lang.Float" target="float32${json} -> SetFloat32"/>-->
        <!--        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>-->
        <!--        <type detected="java.math.BigDecimal" target="float64${json} -> SetFloat64"/>-->

        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->
        <!--        <type detected="byte[]" target="string${json} -> "/>-->
        <!--        <type detected="java.lang.Boolean" target="bool${json} -> SetBool"/>-->

        <!--        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>-->
        <!--        <type detected="java.time.LocalDateTime" target="time:time.Time${json} -> SetTime"/>-->

        <!--        <type detected="java.lang.Object" target="interface{}${json}"/>-->

        <!--        <type detected="java.sql.ResultSet" target="string"/> &lt;!&ndash; PG cursor param &ndash;&gt;-->

        <!-- oracle -->

        <!--        <type detected="sqlx-java.lang.Double" target="float64${json} -> SetFloat64"/>-->
        <!--        <type detected="sqlx-java.math.BigDecimal"-->
        <!--              target="github.com/godror/godror:godror.Number${json-sqlx} -> SetNum"/>-->

        <!--        <type detected="sqlx-java.lang.String" target="string${json-sqlx} -> SetString"/>-->

        <!--        <type detected="sqlx-java.util.Date" target="${json-sqlx-time}"/>-->
        <!--        <type detected="sqlx-java.time.ZonedDateTime" target="${json-sqlx-time}"/>-->
        <!--        <type detected="sqlx-java.time.LocalDateTime" target="${json-sqlx-time}"/>-->

        <!--        <type detected="sqlx-byte[]" target="string${json-sqlx}"/>-->
        <!--        <type detected="sqlx-java.lang.Boolean" target="int64${json-sqlx} -> SetBool"/>-->

        <!--        <type detected="sqlx-java.lang.Object" target="interface{}${json-sqlx}"/>-->

        <!--        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>-->
        <!--        <type detected="java.math.BigDecimal" target="github.com/godror/godror:godror.Number${json} -> SetNum"/>-->

        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->

        <!--        <type detected="java.util.Date" target="${json-time}"/>-->
        <!--        <type detected="java.time.ZonedDateTime" target="${json-time}"/>-->
        <!--        <type detected="java.time.LocalDateTime" target="${json-time}"/>-->

        <!--        <type detected="byte[]" target="string${json}"/>-->
        <!--        <type detected="java.lang.Boolean" target="int64${json} -> SetBool"/>-->

        <!--        <type detected="java.lang.Object" target="interface{}${json}"/>-->

    </type-map>

    <macros>

        <macro value="=built-in=" name="${column}"/>
        <macro value="=built-in=" name="${lower_snake_case(column)}"/>
        <macro value="=built-in=" name="${camelCase(column)}"/>
        <macro value="=built-in=" name="${TitleCase(column)}"/>
        <macro value="=built-in=" name="${kebab-case(column)}"/>

        <macro name="${json-col}" value="${lower_snake_case(column)}"/>

        <macro name="${json-sqlx}" value=" `json:&quot;${json-col}${0}&quot; db:&quot;${column}&quot;`"/>

        <macro name="${json}" value=" `json:&quot;${json-col}${0}&quot;`"/>

        <macro name="${json-sqlx-time}" value="time:time.Time${json-sqlx} -> SetTime"/>

        <macro name="${json-time}" value="time:time.Time${json} -> SetTime"/>

    </macros>


</settings>

=== panedrone/sdm_todolist_go_react_vue_npm_sqlite3/no_orm/sdm/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <folders target="sdm_demo_todolist" sql="no_orm/sdm/sql"/>

    <dto scope="no_orm/dbal/dto" inheritance="" field-names-mode="0" macro=""/>

    <dao scope="no_orm/dbal" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="lib/sqlite-jdbc-3.51.1.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/db/todolist.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

    <!--    <jdbc jar="mysql-connector-j-8.4.0.jar"-->
    <!--          class="com.mysql.cj.jdbc.Driver" url="jdbc:mysql://localhost/orders" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.7.3.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost/orders" user="postgres" pwd="sa"/>-->

    <type-map default="">

        <!-- sqlite3 -->

        <type detected="java.lang.Integer" target="int64${json} -> SetInt64"/>
        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>
        <type detected="java.lang.String" target="string${json} -> SetString"/>
        <type detected="byte[]" target="[]byte${json} -> SetBytes"/>
        <type detected="java.lang.Object" target="interface{}${json}"/>

        <!-- mysql, postgres -->

        <!--        <type detected="java.util.UUID" target="github.com/google/uuid:uuid.UUID${json} -> SetUUID"/>-->
        <!--        <type detected="java.sql.Array" target="[]string${json}"/>-->

        <!--        <type detected="java.lang.Short" target="int16${json} -> SetInt16"/>-->
        <!--        <type detected="java.lang.Integer" target="int32${json} -> SetInt32"/>-->
        <!--        <type detected="java.lang.Long" target="int64${json} -> SetInt64"/>-->

        <!--        <type detected="java.lang.Float" target="float32${json} -> SetFloat32"/>-->
        <!--        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>-->
        <!--        <type detected="java.math.BigDecimal" target="float64${json} -> SetFloat64"/>-->

        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->
        <!--        <type detected="byte[]" target="[]byte${json} -> "/>-->
        <!--        <type detected="java.lang.Boolean" target="bool${json} -> SetBool"/>-->

        <!--        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>-->
        <!--        <type detected="java.time.LocalDateTime" target="time:time.Time${json} -> SetTime"/>-->

        <!--        <type detected="java.lang.Object" target="interface{}${json}"/>-->

        <!-- oracle -->

        <!--        <type detected="java.math.BigDecimal" target="${json-number}"/>-->
        <!--        <type detected="java.math.BigDecimal+auto" target="${json-number}"/>-->
        <!--        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>-->

        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->

        <!--        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>-->
        <!--        <type detected="java.time.ZonedDateTime" target="time:time.Time${json} -> SetTime"/>-->
        <!--        <type detected="java.time.LocalDateTime" target="time:time.Time${json} -> SetTime"/>-->

        <!--        <type detected="byte[]" target="string${json} -> SetBytes"/>-->
        <!--        <type detected="java.lang.Boolean" target="int64${json} -> SetBool"/>-->

        <!--        <type detected="java.lang.Object" target="interface{}${json}"/>-->

    </type-map>

    <macros>

        <macro value="=built-in=" name="${column}"/>
        <macro value="=built-in=" name="${lower_snake_case(column)}"/>
        <macro value="=built-in=" name="${camelCase(column)}"/>
        <macro value="=built-in=" name="${TitleCase(column)}"/>
        <macro value="=built-in=" name="${kebab-case(column)}"/>

        <macro name="${json-col}" value="${lower_snake_case(column)}"/>

        <macro name="${json}" value=" `json:&quot;${json-col}${0}&quot;`"/>

        <macro name="${json-number}" value="${number-type} `json:&quot;${json-col}${0}&quot;` -> ${number-setter}"/>

        <macro name="${number-type}">
            <vm-xml>
                <if var="$fi.Precision == 38 &amp;&amp; $fi.Scale == 0">
                    <print var=" int64"/>
                    <else>
                        <print var=" github.com/godror/godror:godror.Number"/>
                    </else>
                </if>
            </vm-xml>
        </macro>

        <macro name="${number-setter}">
            <vm-xml>
                <if var="$fi.Precision == 38 &amp;&amp; $fi.Scale == 0">
                    <print var=" SetInt64"/>
                    <else>
                        <print var=" SetNum"/>
                    </else>
                </if>
            </vm-xml>
        </macro>

    </macros>

</settings>
